### ISSUE TITLE
Scribe: Generic Event Indexer

### ISSUE THREAD

**Issue by trajan0x** [synapsecns/sanguine#114]
Historically, we've had a lot of issues with missing events from blockchains we operate on. This has resulted in missing transactions and poor/unreliable analytics. Additionally, every service we operate has to tail head in some capacity (for example: synapsecns/sanguine#102 is an external monitoring service).

We can fix this through a generic event sourcing microservice. All off-chain agents + services can run an instance of this service (embedded or separately) and query it rather than querying the chain directly. Notably, this service *can* and _will_ be eth specific so the domain abstractions used in `core` need not apply here.

The service is completely separate from core (new folder in `sanguine`) and has a dedicated config (see: https://github.com/synapsecns/sanguine/tree/master/core/config)

The config might look something like the following:

```yaml
chains:
   - id: 1 # chain id 
     url: "http://127.0.0.1:8545" # rpc url
     confirmation_threshold: 15 # how many blocks to wait before indexing events (so we can account for re-orgs)
   - id: 137
     url: "http://127.0.0.1:8546"

contracts:
   - address: "0x0c4229E35D61d51559Bc450c17337E623179f50b"
    chain_id: 1
    start_block: 2
   - address: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
    chain_id: 137
    start_block: 4
```

The only job of this service is to allow storing and querying of the results of `eth_getLogs` for these contracts. Implementation wise, here's what that looks like:

 - an indexer: starts `eth_getLogs` at a given block and runs it continuously until head and then keeps listening to chain tip. The service will very closely resemble: https://github.com/synapsecns/synapse-node/blob/master/pkg/evm/watcher/contract_watcher.go#L139 Crucially, failure of any kind will not result in continuing to index future blocks outside of the failed range. The failed range will be retried until successful, even across restarts. This means that the latest height has to be persisted.
 
 Events are then idempotently inserted into a database in two parts (and seperate tables) 

[`types.Log`](https://pkg.go.dev/github.com/ethereum/go-ethereum/core/types#Log): all the log data in individual tables so we can query here
[`types.Receipt`](https://pkg.go.dev/github.com/ethereum/go-ethereum/core/types#Receipt): the receipt (which you can fetch using `eth_getTransactionByReceipt`) for the txhash in the log above. Logs in this type (see link) can be fetched using a foreign key constraint. Any logs for contracts we're not watching should be inserted into the logs table as well w/ a foreign key constraint to txhash.

- a query interface: Once the database is done, we want to be able to query over (rest, grpc, etc: up to you) for the following:
  - events for a contract in a given block/time range (GetBlockByTime implemented here: https://github.com/synapsecns/synapse-node/blob/master/pkg/evm/block.go#L21)

That's it. This allows our other services to event source in indexers without worrying about the reliability of the chain and allows individual indexers to break without needing to implement backfilling
